// Templates/StarterFiles/REACT_template.tsx
import React from 'react';

/*
 * Title: [Title of Your Component]
 * Description: [Description of what your component does]
 * Author: [Your Name]
 * Date: [Date]
 */

// Import additional dependencies (if any)


// Define functional component
const YourComponent = () => {
    /*
     * Main function of the component
     */

    // Your code goes here

    return (
        <div>
            {/* JSX content */}
        </div>
    );
};

export default YourComponent;

// Templates/StarterFiles/ANGULAR_template.ts
import { Component, OnInit } from '@angular/core';

/*
 * Title: [Title of Your Component]
 * Description: [Description of what your component does]
 * Author: [Your Name]
 * Date: [Date]
 */

@Component({
  selector: 'app-your-component',
  templateUrl: './your-component.component.html',
  styleUrls: ['./your-component.component.css']
})
export class YourComponent implements OnInit {
  /*
   * Main logic of the component
   */

  constructor() { }

  ngOnInit(): void {
    // Your initialization logic goes here
  }

  // Define additional methods (if any)
}
